version: '3.1'

services:
  db:
    image: postgres:16.0-alpine3.18
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: payment_online
      POSTGRES_PASSWORD: 12345
    ports:
      - "8000:8080"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 12345
    depends_on:
      - db